language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install pytest-cov coverage
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
