on:
  push:
    branches: [ master ]
    paths: [ 'src/**', 'tests/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'src/**', 'tests/**' ]
  pull_request_target:
    branches: [ master ]
    paths: [ 'src/**', 'tests/**' ]
  workflow_dispatch:

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Python
      uses: actions/setup-node@v1
      with:
        python-version: 3.6.8

    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt
        pip install -e .
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
